Navigation bar
Salisbury-University/cyber-security-frontend pull request #7
Opened 2022-04-12 19:15 UTC by Desss64

2022-04-14 13:50 UTC, wrathofrathma requested changes
Fix the requested changes & add the issues.

Also be sure to let me know whether we needed to compile the sass ourselves, or if quasar ended up handling that for us. (If the compilation isn't needed, be sure to get rid of those files).

Besides that, looks good so far.

2022-04-14 13:50 UTC, wrathofrathma commented on src/styles.css
> +/*# sourceMappingURL=styles.css.map */
Was this a quasar thing? Just curious if this was a personal decision to put this here vs in the css part of the App.vue.

2022-04-14 13:50 UTC, wrathofrathma commented on index.html
> -    <title>Vite App</title>
If we're getting rid of the icon & title, we should make an issue to create new ones so we don't forget later.

2022-04-14 13:50 UTC, wrathofrathma commented on src/Layout/Main.vue
> +</script>
Convert this to vuejs script setup tags (and any future script sections should be in script setup format)

```vue
<script setup lang="ts">

</script>
```

The script setup tags cuts down on the amount of boilerplate we need to write. The script setup equivalent of this would be

```vue
<script setup lang="ts">
import { ref } from "vue";

const drawer = ref(false);
const miniState = ref(true);
</script>
```

2022-04-14 13:50 UTC, wrathofrathma commented on src/quasar-variables.css
> +/* No CSS */ /*# sourceMappingURL=quasar-variables.css.map */
Hmm? What is this for?

2022-04-14 13:50 UTC, wrathofrathma commented on src/quasar-variables.css.map
> +}
Is this still needed? I remember there was some potential confusion over whether the sass variables needed to be compiled.

2022-04-14 13:50 UTC, wrathofrathma commented on src/styles.css.map
> +}
Same comment as earlier. Is this needed / do we need to compile the sass? or is it done by quasar by default.

2022-04-14 22:37 UTC, Desss64 commented on src/quasar-variables.css
> +/* No CSS */ /*# sourceMappingURL=quasar-variables.css.map */
Tbh I'm not sure. It was one of the files created when I compiled the sass file as a CSS file.

2022-04-14 22:42 UTC, Desss64 commented on src/quasar-variables.css.map
> +}
It seems that the sass variables only need to be compiled as CSS when I use them in index.html. I was trying to change the background color of the whole page and modified index.html to do so. I'm not sure if there was another way to change the background color without touching the index.html file.

2022-04-14 22:47 UTC, Desss64 commented on src/styles.css
> +/*# sourceMappingURL=styles.css.map */
Not necessarily. It helped me set the background color of the page using a sass variable but I'll try to put it in App.vue.

2022-04-14 23:36 UTC, Desss64 commented on index.html
> -    <title>Vite App</title>
Gotcha, I created the issue for that.

2022-04-15 15:44 UTC, wrathofrathma commented
@JungAn2 don't mind me, testing the pinging

2022-04-17 22:48 UTC, wrathofrathma requested changes
Just fix the one comment and you're approved 👍 don't need to submit for review again

2022-04-17 22:48 UTC, wrathofrathma commented on src/App.vue
> +  background-color: $dark
Does this work without the brackets? 

I know normal CSS it will keep parsing everything before a bracket as the selector. I'm not sure for SASS, but the examples I saw online all had brackets.

I'd say wrap the CSS in brackets and you're good to merge. Doesn't need any further review.

2022-04-18 19:03 UTC, merged